services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_ml
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app_network

  scraper:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
